### ISSUE TITLE
.NET Standard 1 CVE

### ISSUE THREAD

**Issue by null-d3v** [launchdarkly/dotnet-eventsource#58]
Due to the support of .NET Standard 1, there is a security vulnerability in the LaunchDarkly dependency chain that is rooted in EventSource. This is being picked up by SAST scanners and we are currently compelled to use rule exceptions as there is no  workaround to force a package version that does not contain the vulnerability.

Ideally there would be a version of EventSource that did not support .NET Standard 1 that would either be referenced in the chain by `LaunchDarkly.Common.StrongName`, or simply available to override.

The result of scanning, which I believe uses [`dotnet retire`](https://github.com/RetireNet/dotnet-retire):
```
* Microsoft Security Advisory CVE-2018-8416: .NET Core Tampering Vulnerability in System.IO.Compression.ZipFile/4.3.0
https://github.com/dotnet/announcements/issues/95
LaunchDarkly.EventSource/3.3.2
╚ NETStandard.Library/1.6.1
 ╚ System.IO.Compression.ZipFile/4.3.0

* Microsoft Security Advisory CVE-2018-8292: .NET Core Information Disclosure Vulnerability in System.Net.Http/4.3.0
https://github.com/dotnet/announcements/issues/88
LaunchDarkly.EventSource/3.3.2
╚ NETStandard.Library/1.6.1
 ╚ System.IO.Compression.ZipFile/4.3.0
```

**Comment by eli-darkly** [comment]
Thanks for pointing this out. There are a couple of issues here.

First, while I know you are mainly talking about the hassle of having to override the scanner behavior, I'd like to make it clear that this warning is not indicating a real security vulnerability in the library. We don't use `System.IO.Compression.ZipFile` in any way, directly or indirectly. And (I may be wrong here, but I think not) since this is not a matter of an actual package dependency, if the application code or another library used by the application did reference `System.IO.Compression.ZipFile`, the mere presence of a .NET Standard 1.6-targeted package elsewhere in the dependencies would not cause an old insecure version of `ZipFile` to be pulled in. So, as far as I can tell, this is a very broad scanner rule that simply considers any association with .NET Standard 1.x to be tainted.

Second, we were already planning to change the targets for this library (and for our .NET SDK) to .NET Standard 2.0 and .NET Framework 4.5.2 in our next major version releases— you can see there's already a PR for that in this repo.

However, that plan includes dropping .NET Standard 1.4 support at the same time, and we would not normally be doing that prior to the next major version release as it could be considered a breaking change. So our preferred compromise would normally be to release a backward-compatible update to `LaunchDarkly.EventSource` first which adds the 2.0 target, but does not remove the 1.4 target. That would ensure that your application code could not possibly be using the 1.4-targeted build of this library unless you explicitly target 1.4 and not 2.0 (or are referencing this package through another package that targets 1.4 and not 2.0) in which case the scanner would be complaining about your code anyway.

It's unclear whether that would resolve your immediate issue; if the scanner only looks at targets that are actually being used in the dependency chain, then it should. We can try to reproduce this using `dotnet retire` but that's not really proof that it would work the same way in your codebase.

**Comment by eli-darkly** [comment]
Well, I did try to reproduce the issue using `dotnet retire` but I haven't been able to. That is: I created a test app that targets .NET Core 2.0, with a dependency on the latest `LaunchDarkly.EventSource`. And it gets the .NET Standard 1.6 version of the latter. But running `dotnet retire` on this app produces no warnings.

So if that's the tool you're using, there is some difference in how it's configured and I may not be able to reproduce this without knowing more about your configuration. But it might not be necessary for us to reproduce it if you think simply adding the 2.0 target would solve your problem. There's no reason for us _not_ to do that in any case.

**Comment by null-d3v** [comment]
I apologize for opening the redundant issue. I see now the pull request predating it by a day. The CVE exceptions have been in place for a consderable amount time behind others with a higher priority to resolve, during which time I had made note to open an issue and simply did not.

You are not seeing the dotnet retire report because when targeting netstandard2.0, NETStandard.Library will resolve to 2.0.3 and only depend on Microsoft.NETCore.Platforms (>= 1.1.0), the direct target being .NETStandard 2.0. When targeting .NET Core, NETStandard.Library resolves to the lowest viable version of 1.6.1. 1.6.1's nearest underlying dependency collection for the runtime, .NETStandard 1.3, contains the problematic System.IO.Compression.ZipFile and System.Net.Http references.

This path actually results in a more palatable workaround for time being by way of referencing NETStandard.Library 2.0.3 in projects targeting .NET Core. Thanks!

**Comment by eli-darkly** [comment]
> You are not seeing the dotnet retire report because when targeting netstandard2.0, NETStandard.Library will resolve to 2.0.3 and only depend on Microsoft.NETCore.Platforms (>= 1.1.0), the direct target being .NETStandard 2.0. When targeting .NET Core, NETStandard.Library resolves to the lowest viable version of 1.6.1. 1.6.1's nearest underlying dependency collection for the runtime, .NETStandard 1.3, contains the problematic System.IO.Compression.ZipFile and System.Net.Http references.

I appreciate your explanation, but I'm still having some trouble understanding it. The test app that I tried to reproduce this with _does_ target .NET Core. How does this differ from your application's build?

**Comment by eli-darkly** [comment]
I'm also wondering whether the dependency on `Common.Logging`, which has only a .NET Standard 1.3 target, will continue to cause this issue even if `LaunchDarkly.EventSource` and the LaunchDarkly SDK are updated.

**Comment by null-d3v** [comment]
This is the csproj I am using to track dependency graphs
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LaunchDarkly.EventSource" Version="3.3.2" />
  </ItemGroup>
</Project>
```

When I run a restore on the above targeting netcoreapp3.1 or net5.0, my project assets indicate the following dependency data:
```
      "NETStandard.Library/1.6.1": {
        "type": "package",
        "dependencies": {
          "Microsoft.NETCore.Platforms": "1.1.0",
          "Microsoft.Win32.Primitives": "4.3.0",
          "System.AppContext": "4.3.0",
          "System.Collections": "4.3.0",
          "System.Collections.Concurrent": "4.3.0",
          "System.Console": "4.3.0",
          "System.Diagnostics.Debug": "4.3.0",
          "System.Diagnostics.Tools": "4.3.0",
          "System.Diagnostics.Tracing": "4.3.0",
          "System.Globalization": "4.3.0",
          "System.Globalization.Calendars": "4.3.0",
          "System.IO": "4.3.0",
          "System.IO.Compression": "4.3.0",
          "System.IO.Compression.ZipFile": "4.3.0",
          "System.IO.FileSystem": "4.3.0",
          "System.IO.FileSystem.Primitives": "4.3.0",
          "System.Linq": "4.3.0",
          "System.Linq.Expressions": "4.3.0",
          "System.Net.Http": "4.3.0",
          "System.Net.Primitives": "4.3.0",
          "System.Net.Sockets": "4.3.0",
          "System.ObjectModel": "4.3.0",
          "System.Reflection": "4.3.0",
          "System.Reflection.Extensions": "4.3.0",
          "System.Reflection.Primitives": "4.3.0",
          "System.Resources.ResourceManager": "4.3.0",
          "System.Runtime": "4.3.0",
          "System.Runtime.Extensions": "4.3.0",
          "System.Runtime.Handles": "4.3.0",
          "System.Runtime.InteropServices": "4.3.0",
          "System.Runtime.InteropServices.RuntimeInformation": "4.3.0",
          "System.Runtime.Numerics": "4.3.0",
          "System.Security.Cryptography.Algorithms": "4.3.0",
          "System.Security.Cryptography.Encoding": "4.3.0",
          "System.Security.Cryptography.Primitives": "4.3.0",
          "System.Security.Cryptography.X509Certificates": "4.3.0",
          "System.Text.Encoding": "4.3.0",
          "System.Text.Encoding.Extensions": "4.3.0",
          "System.Text.RegularExpressions": "4.3.0",
          "System.Threading": "4.3.0",
          "System.Threading.Tasks": "4.3.0",
          "System.Threading.Timer": "4.3.0",
          "System.Xml.ReaderWriter": "4.3.0",
          "System.Xml.XDocument": "4.3.0"
        }
      },
```
with my `frameworks` section appearing as:
```
"frameworks": {
  "net5.0": {
    "targetAlias": "net5.0",
    "dependencies": {
      "LaunchDarkly.EventSource": {
        "target": "Package",
        "version": "[3.3.2, )"
      }
    },
    "imports": [
      "net461",
      "net462",
      "net47",
      "net471",
      "net472",
      "net48"
    ],
    "assetTargetFallback": true,
    "warn": true,
    "frameworkReferences": {
      "Microsoft.NETCore.App": {
        "privateAssets": "all"
      }
    },
    "runtimeIdentifierGraphPath": "C:\\Program Files\\dotnet\\sdk\\5.0.100-rc.2.20479.15\\RuntimeIdentifierGraph.json"
  }
}
```

When targeting netstandard2.0, I see the following:
```
"NETStandard.Library/2.0.3": {
  "type": "package",
  "dependencies": {
    "Microsoft.NETCore.Platforms": "1.1.0"
  },
  "compile": {
    "lib/netstandard1.0/_._": {}
  },
  "runtime": {
    "lib/netstandard1.0/_._": {}
  },
  "build": {
    "build/netstandard2.0/NETStandard.Library.targets": {}
  }
},
```
with my `frameworks` sections appearing as:
```
"frameworks": {
  "netstandard2.0": {
    "targetAlias": "netstandard2.0",
    "dependencies": {
      "LaunchDarkly.EventSource": {
        "target": "Package",
        "version": "[3.3.2, )"
      },
      "NETStandard.Library": {
        "suppressParent": "All",
        "target": "Package",
        "version": "[2.0.3, )",
        "autoReferenced": true
      }
    },
    "imports": [
      "net461",
      "net462",
      "net47",
      "net471",
      "net472",
      "net48"
    ],
    "assetTargetFallback": true,
    "warn": true,
    "runtimeIdentifierGraphPath": "C:\\Program Files\\dotnet\\sdk\\5.0.100-rc.2.20479.15\\RuntimeIdentifierGraph.json"
  }
}
```

**Comment by eli-darkly** [comment]
Sorry, I'm still a bit confused. Is your project an application or a library? Since you mentioned targeting netcoreapp3.1, I assumed it was an application. But then you mentioned switching the target to netstandard2.0, which would only make sense for a library.

I'm also still not sure how the file data you excerpted is related to reproducing the original symptom you described. I do see that there is a reference to NETStandard.Library 1.6.1, as you said. But I'm not seeing how that in itself would cause the warning you described, since your assets are not showing any transitive references to `System.IO.Compression.ZipFile`.

In any case: we've just released a patch of this library that adds a netstandard2.0 target, and we released corresponding patches of the SDK packages that use this. I don't know if it'll resolve your issue— I think it's possible that other transitive dependencies will still bring in a reference to the 1.6 runtime. But it was a reasonable thing to do anyway, and we're continuing to update dependencies in the next major SDK versions. Please let us know if you get a chance to try the patch release.
