### ISSUE TITLE
Exception when trying to startup LdClient with Event Source

### ISSUE THREAD

**Issue by jeffrey-vang** [launchdarkly/dotnet-eventsource#72]
Error trying to initialize LDClient with SDK key.
Error: 
```
System.MethodAccessException: Attempt by method 'LaunchDarkly.Common.StreamManager..ctor(LaunchDarkly.Common.IStreamProcessor, LaunchDarkly.Common.StreamProperties, LaunchDarkly.Common.IBaseConfiguration, LaunchDarkly.Common.ClientEnvironment, EventSourceCreator)' to access method 'LaunchDarkly.EventSource.ExponentialBackoffWithDecorrelation..ctor(System.TimeSpan, System.TimeSpan)' failed..
```

Using packages:
- LaunchDarkly.Client v5.6.3
- LaunchDarkly.EventSource v4.0.0

**Comment by eli-darkly** [comment]
There are two problems here:

1. Using an out-of-date SDK: 5.6.3 was the last release of the NuGet package called `LaunchDarkly.Client`, almost two years ago. As you'll see in the [documentation](https://docs.launchdarkly.com/sdk/server-side/dotnet) and the [changelog](https://github.com/launchdarkly/dotnet-server-sdk/blob/master/CHANGELOG.md#564---2019-05-10), the package name was changed to `LaunchDarkly.ServerSdk` starting in 5.6.4.
2. Updating `LaunchDarkly.EventSource` separately from the SDK package. There is a specific dependency version of `LaunchDarkly.EventSource` for each version of the SDK package. That is the one it wants (and the same goes for any other LaunchDarkly packages that the SDK references). Since we follow semantic versioning, it should be OK to update a dependency to a later _minor_ version— but it is never a good idea to update to a later _major_ version (in this case, from 3.x to 4.0) because, by definition, new major versions are likely to be backward-incompatible. The 4.0.0 release of `LaunchDarkly.EventSource` is not meant for this version of the SDK, but for the upcoming 6.0 version.

If you're using .NET Core, you should never need to add or update transitive dependencies explicitly— your application should only have a dependency on the SDK itself, not on any of the other things the SDK uses. Then you'll always be getting the right version.

If you're using ASP.NET, unfortunately it will default to using the old-style "packages.json" format for dependencies, and it will add in all of the transitive dependencies there explicitly when you install the SDK, so there's no way to avoid having them listed as dependencies of your app. But, instead of trying to update those separately, the right way to go is to uninstall all of the LaunchDarkly packages and then install the new version of the SDK— causing it to bring in the correct versions of the transitive dependencies for that version.
