### ISSUE TITLE
Make the EventSource-class extensible

### ISSUE THREAD

**Issue by AlexanderMelchers** [launchdarkly/dotnet-eventsource#81]
It would be great if the [`EventSource.OnMessageReceived`](https://github.com/launchdarkly/dotnet-eventsource/blob/aef3e05dad69180c7f6fa5d99a025247436d1275/src/LaunchDarkly.EventSource/EventSource.cs#L461)-method, [`EventSource.DispatchEvent`](https://github.com/launchdarkly/dotnet-eventsource/blob/aef3e05dad69180c7f6fa5d99a025247436d1275/src/LaunchDarkly.EventSource/EventSource.cs#L417) (or an intermediary) could be made `virtual` so that custom message processing could be implemented by inheriting from the `EventSource`-class and overriding this method.

As a concrete example, I'd like to extend the class with a method for adding and removing listeners for specific events (which may, in itself, be a nice additional feature), for which I'd need to hook into the message handling loop. However, at present, I can only do so by subscribing to the `MessageReceived`-event.

**Comment by eli-darkly** [comment]
We've tried to keep to standard language idioms for these libraries, and event handlers are standard in .NET. I'm not sure what problem you're trying to solve— you mentioned what you want to do, but not why.

Also, we've avoided providing overridable methods on the general principle that object-oriented inheritance is often a problematic pattern. That's a philosophical judgment call of course, and a can of worms that I'd rather not get into here, but from my point of view as a maintainer of the library, the main issues are 1. it creates constraints on us that may make it hard to maintain the code, because now we are locked into always having this public method that behaves in this way; 2. inheritance requires the subclass to call the base class constructor, so if we want to add any features that would involve changes to the constructor, the subclass will not be able to use them.

So I think it's safe to say that if we were going to implement some kind of customizability like you're suggesting, we would want to do it with composition rather than inheritance (e.g. passing in a function). But it's still unclear to me what the goal is.

**Comment by AlexanderMelchers** [comment]
Hi @eli-darkly,

Thanks for responding to my question. Of course I understand that any choice in computer programming is ultimately a philosophical one - and, when it comes to that, I do really like the approach taken in this library, with the difference that I would normally have made the methods firing events virtual, exactly for extensibility purposes, or otherwise have marked the class `sealed` to make my intentions clear. Call me old-school, however, but I still very much prefer object-inheritance over object-composition (although there are certainly uses for the latter), something I believe is also echo by standard .NET.

Philosophical matters aside, though, as I have no doubt we could delve into this topic endlessly (such as that I think that the generic way the constructors are implemented now is likely to lead only to addition of overrides and/or parameters, if at all, not their removal), the reason I wanted to extend the class' functionality is to split out message processing. Currently, there's only one event handler that'll fire whenever a message is received, irrespective of the server-event that triggered it. Rather than implementing the `MessageReceived`-handler as a message-router that invokes individual message processing methods depending on server-event received - code that I believe would, in a general sense, be duplicated whenever a new `EventSource`-implementation is written - or even - god forbid - writing all message processing in one event-handler, however, I would like the `EventSource` to automagically route events to the correct handler for me. My solution to this is to implement listeners for individual events, following the observer-pattern. Now I know this is mostly a Java (hence Android) and JavaScript pattern, but it is more extensible than simple event handling by, in a way, using object-composition principles.

Here's my class implementation as a quick (and hence not necessarily perfect) example:
```
    public class CustomEventSource : EventSource
    {
        private readonly IDictionary<string, Action<MessageEvent>> _listeners =
            new Dictionary<string, Action<MessageEvent>>(StringComparer.OrdinalIgnoreCase);

        public CustomEventSource(Configuration configuration)
            : base(configuration)
        {
            MessageReceived += OnMessageReceived;
        }

        public CustomEventSource(Uri uri)
            : base(uri)
        {
            MessageReceived += OnMessageReceived;
        }

        public CustomEventSource AddListener(string eventName, Action<MessageEvent> action)
        {
            _ = action ?? throw new ArgumentNullException(nameof(action));
            _listeners.Add(GetTrueEventName(eventName), action);

            return this;
        }

        public CustomEventSource RemoveListener(string eventName)
        {
            _listeners.Remove(GetTrueEventName(eventName));

            return this;
        }

        private void OnMessageReceived(object sender, MessageReceivedEventArgs e)
        {
            var eventName = GetTrueEventName(e.EventName);
            if (_listeners.TryGetValue(eventName, out Action<MessageEvent> action))
            {
                action(e.Message);
            }
        }

        private string GetTrueEventName(string eventName)
            => string.IsNullOrWhiteSpace(eventName) ? "message" : eventName.Trim();
    }
```

This is then used as follows:
```
            var client = new CustomEventSource(configuration.Build())
                .AddListener("eventName", message =>
                {
                    // event processing
                });
```

Of course this could even be extended to automatically perform deserialization for the listener, although this would then likely require some form of reflection to make it work, and therefore be less desirable.

Anyway, this was/is my consideration, which I hope is a bit clearer now...

Lastly, as another interesting philosophical matter, I believe the `EventSource` would lend itself perfectly for the use of observables through Reactive Extensions. That way you might actually be able to easily split out different server-events for separate processing outside of the class itself, by simply publishing events as they come onto the chain, and then filtering for specific events on each subsequent chain...

**Comment by eli-darkly** [comment]
Again, as you just acknowledged, you are talking about a very general issue with the use of event handlers in a garbage-collected language; I think your issue is more with the .NET platform and C# language than with this library. If you want to build something on top of EventSource to entirely change how its API works, you're welcome to do so, and you can easily do it without subclassing: just create a class X that owns an EventSource instance and sets its MessageReceived event to point to a method of X. Presto, you're done: now if you dispose of your X instance, it can ensure that the EventSource is also disposed of.

That usage pattern may make sense for your application but I don't see reason to think that it's also what other developers will want, so again I think the best choice is to stick with a simple model here and allow people to plug into it whatever they want. And, again, that's basically what every HTTP server framework and every other kind of library out there that has a general message handler model does. If you raised an issue like this for an HTTP server library and suggested that it'd be better to subclass the server than to implement a router separately, I'm pretty sure you would get an identical response.
