### ISSUE TITLE
Question: Is there a sample code to know how to use this library?

### ISSUE THREAD

**Issue by MujanMujan** [launchdarkly/dotnet-eventsource#91]

**Comment by eli-darkly** [comment]
Currently no, just the [API reference](https://launchdarkly.github.io/dotnet-eventsource/api/LaunchDarkly.EventSource.html). Like all of the LaunchDarkly SSE implementations, this library exists because it's needed by other LaunchDarkly projects (https://launchdarkly.github.io/dotnet-server-sdk/, https://launchdarkly.github.io/dotnet-client-sdk/), so even though it can definitely be used for other purposes, we haven't focused on building out its own documentation.

I can write you a couple of examples right here, though.

**Comment by eli-darkly** [comment]
Basically, any application that wants to use this to read an SSE stream needs to do the following things, at a minimum:

1. Configure and create the `EventSource`. If you don't need any custom behavior, all you need is the URI of the stream you're connecting to:

```csharp
    var eventSource = new EventSource(new Uri("https://my-stream-server.com/whatever-uri-path"));
```

Or if you need other configuration:

```csharp
    var builder = Configuration.Builder(new Uri("https://my-stream-server.com/whatever-uri-path"))
        .RequestHeader("some-header-name", "header-value") // or whatever other options you want
        .Build();
    var eventSource = new EventSource(builder.Build());
```

2. Specify a handler that the EventSource will call when it receives messages on the stream.

```csharp
    eventSource.MessageReceived += (sender, eventArgs) => {
        var eventName = eventArgs.Message.Name;
        var eventData = eventArgs.Message.Data;
        // do whatever you want to do with the message
    }
```

3. Tell the EventSource to connect to the stream. Once connected, it continues to run in the background and will automatically reconnect whenever the connection is broken, unless you have configured custom error-handling behavior with the ConfigurationBuilder options.

```csharp
    Task.Run(() => eventSource.StartAsync());
```

**Comment by eli-darkly** [comment]
I hope that's helpful.

**Comment by MujanMujan** [comment]
Thanks a lot @eli-darkly . That's what I wanted.

**Comment by qcjxberin** [comment]
How to implement the failure to restart when the link is broken?
